-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 11:12:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBcheckpoint4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBcheckpoint4` ;

-- -----------------------------------------------------
-- Schema DBcheckpoint4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBcheckpoint4` DEFAULT CHARACTER SET utf8 ;
USE `DBcheckpoint4` ;

-- -----------------------------------------------------
-- Table `DBcheckpoint4`.`Makers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBcheckpoint4`.`Makers` ;

CREATE TABLE IF NOT EXISTS `DBcheckpoint4`.`Makers` (
  `idMakers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMakers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBcheckpoint4`.`Years`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBcheckpoint4`.`Years` ;

CREATE TABLE IF NOT EXISTS `DBcheckpoint4`.`Years` (
  `idYears` INT NOT NULL AUTO_INCREMENT,
  `Year` INT NOT NULL,
  PRIMARY KEY (`idYears`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBcheckpoint4`.`Consoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBcheckpoint4`.`Consoles` ;

CREATE TABLE IF NOT EXISTS `DBcheckpoint4`.`Consoles` (
  `idConsoles` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(255) NOT NULL,
  `Makers_idMakers` INT NOT NULL,
  `Years_idYears` INT NOT NULL,
  PRIMARY KEY (`idConsoles`, `Makers_idMakers`, `Years_idYears`),
  INDEX `fk_Consoles_Makers_idx` (`Makers_idMakers` ASC) VISIBLE,
  INDEX `fk_Consoles_Years1_idx` (`Years_idYears` ASC) VISIBLE,
  CONSTRAINT `fk_Consoles_Makers`
    FOREIGN KEY (`Makers_idMakers`)
    REFERENCES `DBcheckpoint4`.`Makers` (`idMakers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consoles_Years1`
    FOREIGN KEY (`Years_idYears`)
    REFERENCES `DBcheckpoint4`.`Years` (`idYears`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBcheckpoint4`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBcheckpoint4`.`Games` ;

CREATE TABLE IF NOT EXISTS `DBcheckpoint4`.`Games` (
  `idGames` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Consoles_idConsoles` INT NOT NULL,
  `Years_idYears` INT NOT NULL,
  PRIMARY KEY (`idGames`, `Consoles_idConsoles`, `Years_idYears`),
  INDEX `fk_Games_Consoles1_idx` (`Consoles_idConsoles` ASC) VISIBLE,
  INDEX `fk_Games_Years1_idx` (`Years_idYears` ASC) VISIBLE,
  CONSTRAINT `fk_Games_Consoles1`
    FOREIGN KEY (`Consoles_idConsoles`)
    REFERENCES `DBcheckpoint4`.`Consoles` (`idConsoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Games_Years1`
    FOREIGN KEY (`Years_idYears`)
    REFERENCES `DBcheckpoint4`.`Years` (`idYears`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
